In [23]:
import sys
sys.path.append("..")

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

### File list


In [24]:
excel_file = ["CHARM_Example-MC_Scenarios_v2.xlsx","CHARM_Example-MC_Scenarios_v3.xlsx"]

worksheets = ["Base Case","Scenario 1","Scenario 2","Scenario 3","Scenario 4"
             ,"Scenario 5","Scenario 6","Scenario 7","Scenario 8"]
num_sample = 500

In [25]:
excel_path = "C://Users//Administrator//Desktop//Code_Test//Evaluation_Data_MC_scenarios//data//"

### Processing excel file


In [26]:
import os
excel_file_path = os.path.join(excel_path,excel_file[0])
excel_file_path

'C://Users//Administrator//Desktop//Code_Test//Evaluation_Data_MC_scenarios//data//CHARM_Example-MC_Scenarios_v2.xlsx'

In [27]:
xls = pd.ExcelFile(excel_file_path)

In [28]:
def extract_feature(sheet, num_samples):
    matrix_numpy = []
    for i in range(num_sample):
        matrix_numpy.append(sheet.loc[i,:].to_numpy())
    return matrix_numpy

In [29]:
D = []
for worksheet in worksheets:
    df = pd.read_excel(xls,worksheet)
    matrix_feature = extract_feature(df, num_sample)
    D.append(matrix_feature)
    matrix = np.asarray(D)

In [30]:
data_feature = matrix.reshape(matrix.shape[0]*matrix.shape[1], matrix.shape[2])
data_feature

array([[128706.54805375, 128975.9417411 , 130854.81103233, ...,
             0.        ,      0.        ,      0.        ],
       [125259.70747691, 140049.93558556, 117696.08631165, ...,
             0.        ,      0.        ,      0.        ],
       [138165.81400699, 121071.34507232, 123397.4663427 , ...,
             0.        ,      0.        ,      0.        ],
       ...,
       [121418.29747666, 132343.41716457, 125918.55546108, ...,
             0.        ,      0.        ,      0.        ],
       [132624.63252299, 131513.04088131, 114934.65913607, ...,
             0.        ,      0.        ,      0.        ],
       [122999.49778842, 129360.37188858, 122071.51735841, ...,
             0.        ,      0.        ,      0.        ]])

In [31]:
X_train_full = data_feature[:,0:13]
X_test_full = data_feature[:,13:26]

In [32]:
X_train, X_test, y_train, y_test = train_test_split(X_train_full, X_test_full, test_size=0.2, random_state=42)

## MultiOutputRegressor

In [33]:
import numpy as np
from sklearn.multioutput import MultiOutputRegressor

In [39]:
from sklearn.linear_model import Lars

In [4]:
from sklearn.linear_model import LinearRegression

In [7]:
algo_name = LinearRegression()
algo_name.__class__.__name__

'LinearRegression'

In [50]:
from sklearn.svm import LinearSVR
from sklearn.multioutput import RegressorChain

In [51]:
model = LinearSVR()
clf = RegressorChain(model).fit(X_train, y_train)

c:\programdata\anaconda3\envs\python36\lib\site-packages\sklearn\svm\_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
c:\programdata\anaconda3\envs\python36\lib\site-packages\sklearn\svm\_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
c:\programdata\anaconda3\envs\python36\lib\site-packages\sklearn\svm\_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
c:\programdata\anaconda3\envs\python36\lib\site-packages\sklearn\svm\_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
c:\programdata\anaconda3\envs\python36\lib\site-packages\sklearn\svm\_base.py:947: ConvergenceWarning: Liblinear failed to c

clf = MultiOutputRegressor(LassoLars(alpha=.1)).fit(X_train, y_train)

In [55]:
y_predict = clf.predict(X_test)
y_predict

array([[ -163.99118989,  -642.63217152,   279.62760709, ...,
            0.        ,     0.        ,     0.        ],
       [  274.91293011, -2361.82861954,   551.72749939, ...,
            0.        ,     0.        ,     0.        ],
       [  183.12399671,   336.69160233,  1116.69032755, ...,
            0.        ,     0.        ,     0.        ],
       ...,
       [  101.81182901,   279.58012416,  1360.27887887, ...,
            0.        ,     0.        ,     0.        ],
       [ -102.42469317, -1111.73921272,   158.7834873 , ...,
            0.        ,     0.        ,     0.        ],
       [ -655.62754396, -2245.27242096,   243.6051263 , ...,
            0.        ,     0.        ,     0.        ]])

In [61]:
np.concatenate((y_predict,y_test), axis =  1).shape

(900, 26)

### Mean Squared Error

In [52]:
from sklearn.metrics import mean_squared_error

In [53]:
mean_squared_error(y_test, y_predict)

13209592.932760775

### Mean Absolute Error

In [54]:
from sklearn.metrics import mean_absolute_error

In [55]:
mean_absolute_error(y_test, y_predict)

1291.1762409739483

### Explained Variance Score

In [56]:
from sklearn.metrics import explained_variance_score

In [57]:
explained_variance_score(y_test, y_predict)

0.7317443247745115

In [4]:
from sklearn.metrics import mean_squared_error
y_true = [3, -0.5, 2, 7]
y_pred = [2.5, 0.0, 2, 8]
mean_squared_error.__class__.__name__

'function'

In [13]:
mean_squared_error.__name__

'mean_squared_error'

In [9]:
import numpy as np

a = np.random.randint(5, size=(5,2))
print(a)
b = np.random.randint(10, size=(5,2))
print(b)
np.concatenate((a,b,abs(a-b)),axis = 1)

[[4 3]
 [4 4]
 [3 4]
 [0 2]
 [1 3]]
[[5 4]
 [8 1]
 [8 3]
 [2 8]
 [8 2]]


array([[4, 3, 5, 4, 1, 1],
       [4, 4, 8, 1, 4, 3],
       [3, 4, 8, 3, 5, 1],
       [0, 2, 2, 8, 2, 6],
       [1, 3, 8, 2, 7, 1]])

In [38]:
a = np.random.rand((5,2))
a

TypeError: 'tuple' object cannot be interpreted as an integer

In [46]:
from numpy import inf
b = 1/a
print(b)
b[b==inf] = 0
print(b)


c = abs(a-b)
print(c)
d = c * b



[[0.25       0.33333333]
 [0.5        0.5       ]
 [       inf 1.        ]
 [0.33333333        inf]
 [0.33333333        inf]]
[[0.25       0.33333333]
 [0.5        0.5       ]
 [0.         1.        ]
 [0.33333333 0.        ]
 [0.33333333 0.        ]]
[[3.75       2.66666667]
 [1.5        1.5       ]
 [0.         0.        ]
 [2.66666667 0.        ]
 [2.66666667 0.        ]]


c:\programdata\anaconda3\envs\python36\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


In [48]:
d.shape[1]

2

In [13]:
0**-1

ZeroDivisionError: 0.0 cannot be raised to a negative power